# Generated by Django 6.0.5 on 2026-07-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.IntegerField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('EmployeeSalary', models.IntegerField()),
            ],
        ),
    ]
